import { Header } from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Footer } from "@/components/Footer";
import Link from "next/link";

const roboto = Roboto({ weight: "300", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className}  max-w-7xl min-h-screen m-auto flex flex-col p-5`}
      >
        <Header.Root>
          <Header.Logo />
          <Header.Nav>
            <Header.NavItem>
              <Link href="/blog">Blog</Link>
            </Header.NavItem>
            <Header.NavItem>
              <Link href="/about">Sobre</Link>
            </Header.NavItem>
          </Header.Nav>
        </Header.Root>

        {children}

        <Footer.Root>
          <Footer.SocialLinks>
            <Footer.SocialLink
              name="Github"
              link="https://github.com/crisgon"
            />
            <Footer.SocialLink
              name="Twitter"
              link="https://twitter.com/Gonkristiano"
            />
            <Footer.SocialLink
              name="Linkedin"
              link="https://www.linkedin.com/in/cristiano-gon%C3%A7alves/"
            />
          </Footer.SocialLinks>
        </Footer.Root>
      </body>
    </html>
  );
}
